name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Run tests with coverage
      run: npm run test:coverage
    
    - name: Upload coverage to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-node-${{ matrix.node-version }}
        path: coverage/
    
    - name: Update README with coverage
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.node-version == '20.x'
      run: |
        # Получаем данные о покрытии
        LINES_COVERAGE=$(cat coverage/lcov-report/index.html | grep -o 'statements.*%' | sed 's/statements\s*:\s*\([0-9.]*\)%/\1/')
        FUNCTIONS_COVERAGE=$(cat coverage/lcov-report/index.html | grep -o 'functions.*%' | sed 's/functions\s*:\s*\([0-9.]*\)%/\1/')
        BRANCHES_COVERAGE=$(cat coverage/lcov-report/index.html | grep -o 'branches.*%' | sed 's/branches\s*:\s*\([0-9.]*\)%/\1/')
        
        # Обновляем README.md
        sed -i "s/- Строки: [0-9.]*%/- Строки: ${LINES_COVERAGE}%/" README.md
        sed -i "s/- Функции: [0-9.]*%/- Функции: ${FUNCTIONS_COVERAGE}%/" README.md
        sed -i "s/- Ветвления: [0-9.]*%/- Ветвления: ${BRANCHES_COVERAGE}%/" README.md
        
        # Настраиваем Git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Коммитим изменения
        git add README.md
        git commit -m "Update coverage in README [skip ci]"
        git push 