name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Run tests with coverage
      run: npm run test:coverage
    
    - name: Upload coverage to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-node-${{ matrix.node-version }}
        path: coverage/
    
    - name: Update README with coverage
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.node-version == '20.x'
      run: |
        # Получаем данные о покрытии напрямую из отчета
        LINES_PERCENTAGE=$(cat coverage/lcov-report/index.html | grep -o 'Statements.*%' | sed 's/Statements.*>\([0-9.]*\)%/\1/')
        FUNCTIONS_PERCENTAGE=$(cat coverage/lcov-report/index.html | grep -o 'Functions.*%' | sed 's/Functions.*>\([0-9.]*\)%/\1/')
        BRANCHES_PERCENTAGE=$(cat coverage/lcov-report/index.html | grep -o 'Branches.*%' | sed 's/Branches.*>\([0-9.]*\)%/\1/')
        
        # Выводим данные для отладки
        echo "Покрытие строк: $LINES_PERCENTAGE%"
        echo "Покрытие функций: $FUNCTIONS_PERCENTAGE%"
        echo "Покрытие ветвлений: $BRANCHES_PERCENTAGE%"
        
        # Обновляем README.md
        sed -i "s/- Строки: .*%/- Строки: $LINES_PERCENTAGE%/" README.md
        sed -i "s/- Функции: .*%/- Функции: $FUNCTIONS_PERCENTAGE%/" README.md
        sed -i "s/- Ветвления: .*%/- Ветвления: $BRANCHES_PERCENTAGE%/" README.md
        
        # Проверяем изменения
        git diff README.md
        
        # Настраиваем Git
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Коммитим изменения
        git add README.md
        git commit -m "Update coverage in README [skip ci]"
        git push 