name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Run tests with coverage
      run: npm run test:coverage
    
    - name: Upload coverage to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-node-${{ matrix.node-version }}
        path: coverage/
    
    - name: Update README with coverage
      if: github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.node-version == '20.x'
      run: |
        # Выводим содержимое файла с отчетом о покрытии для отладки
        echo "Содержимое файла с отчетом о покрытии:"
        cat coverage/lcov-report/index.html | grep -A 10 "clearfix"
        
        # Получаем данные о покрытии из файла lcov.info
        LINES_COVERAGE=$(grep -A 3 "SF:" coverage/lcov.info | grep "LF:" | head -1 | cut -d ":" -f 2)
        LINES_COVERED=$(grep -A 3 "SF:" coverage/lcov.info | grep "LH:" | head -1 | cut -d ":" -f 2)
        LINES_PERCENTAGE=$(echo "scale=2; $LINES_COVERED * 100 / $LINES_COVERAGE" | bc)
        
        BRANCHES_COVERAGE=$(grep -A 10 "SF:" coverage/lcov.info | grep "BRF:" | head -1 | cut -d ":" -f 2)
        BRANCHES_COVERED=$(grep -A 10 "SF:" coverage/lcov.info | grep "BRH:" | head -1 | cut -d ":" -f 2)
        BRANCHES_PERCENTAGE=$(echo "scale=2; $BRANCHES_COVERED * 100 / $BRANCHES_COVERAGE" | bc)
        
        FUNCTIONS_COVERAGE=$(grep -A 6 "SF:" coverage/lcov.info | grep "FNF:" | head -1 | cut -d ":" -f 2)
        FUNCTIONS_COVERED=$(grep -A 6 "SF:" coverage/lcov.info | grep "FNH:" | head -1 | cut -d ":" -f 2)
        FUNCTIONS_PERCENTAGE=$(echo "scale=2; $FUNCTIONS_COVERED * 100 / $FUNCTIONS_COVERAGE" | bc)
        
        # Выводим данные для отладки
        echo "Покрытие строк: $LINES_PERCENTAGE%"
        echo "Покрытие функций: $FUNCTIONS_PERCENTAGE%"
        echo "Покрытие ветвлений: $BRANCHES_PERCENTAGE%"
        
        # Обновляем README.md
        sed -i "s/- Строки: .*%/- Строки: $LINES_PERCENTAGE%/" README.md
        sed -i "s/- Функции: .*%/- Функции: $FUNCTIONS_PERCENTAGE%/" README.md
        sed -i "s/- Ветвления: .*%/- Ветвления: $BRANCHES_PERCENTAGE%/" README.md
        
        # Проверяем изменения
        git diff README.md
        
        # Настраиваем Git
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Коммитим изменения
        git add README.md
        git commit -m "Update coverage in README [skip ci]"
        git push 